### PR TITLE
Overwrite dnsmasq conf instead of abort

### LINKED ISSUE #153: `govuk-docker doctor` dnsmasq check fails on comments in /etc/resolver/...
If you have something like this in `/etc/resolver/dev.gov.uk`:

```
# some comment
nameserver 127.0.0.1
```

...then `govuk-docker doctor` fails with:

```
❌ Something else (possibly Vagrant-dns) is configured to resolve DNS requests for dev.gov.uk.
          The /etc/resolver/dev.gov.uk file needs to be updated to only contain
          nameserver 127.0.0.1
```

It should ignore comments, as we can save new joiners a few moments of confusion by not erroring on comments. Comments were in `/etc/resolver/dev.gov.uk` by default on mine and @AgaDufrat's machines, so I suspect a lot of devs come across this.

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Previously, if dnsmasq conf already exists then the setup command
would return without writing to it, which meant that the DNS may
not be configured properly.

After some discussion (https://github.com/alphagov/govuk-docker/pull/168\#issuecomment-519891271)
we've concluded that there is no foreseeable scenario whereby a
developer will need to ever configure this file manually, so we
should be able to overwrite it safely.

'govuk-docker doctor' now fails if /etc/resolver/dev.gov.uk is in
any way different to dnsmasq.conf in govuk-docker.

Arises from #168.

Fixes #153.

### CODE REVIEW

File: lib/govuk_docker/doctor/doctor.rb [hunk 1]
```diff
@@ -67,10 +67,8 @@ def self.dnsmasq_messages
       HEREDOC
       dnsmasq_resolver: "✅ Dnsmasq is resolving DNS requests",
       not_dnsmasq_resolver: <<~HEREDOC,
-        ❌ Something else (possibly Vagrant-dns) is configured to resolve DNS requests for dev.gov.uk.
-          The /etc/resolver/dev.gov.uk file needs to be updated to only contain
-          nameserver 127.0.0.1
-          port 53
+        ❌ Your DNS resolver file (/etc/resolver/dev.gov.uk) is out of date with govuk-docker.
+        It should be overwritten with the contents of ~/govuk/govuk-docker/config/dnsmasq.conf
```
Comment (thomasleese) [inline lib/govuk_docker/doctor/doctor.rb]: We should use `govuk_docker_dir` here to generate this path.

File: lib/govuk_docker/doctor/checkup.rb [hunk 2]
```diff
@@ -87,7 +87,7 @@ def running_user_message
     end
 
     def dnsmasq_resolver?
-      File.read('/etc/resolver/dev.gov.uk').strip == "nameserver 127.0.0.1\nport 53"
+      File.read('/etc/resolver/dev.gov.uk') == File.read(File.join(GovukDocker::Paths::govuk_docker_dir, 'config', 'dnsmasq.conf'))
```
Comment (thomasleese) [inline lib/govuk_docker/doctor/checkup.rb]: It might be worth extracting `File.join(GovukDocker::Paths::govuk_docker_dir, 'config', 'dnsmasq.conf'` into a variable or method here as this line is quite long.

File: lib/govuk_docker/setup/dnsmasq.rb [hunk 3]
```diff
@@ -44,7 +44,8 @@ def install_dnsmasq
   def configure_etc_resolver_devgovuk
     write_file(
       "/etc/resolver/dev.gov.uk",
-      "nameserver 127.0.0.1\nport 53"
+      File.read(File.join(GovukDocker::Paths::govuk_docker_dir, 'config', 'dnsmasq.conf')),
```
Comment (thomasleese) [inline lib/govuk_docker/setup/dnsmasq.rb]: Same thing about extracting this out into a variable or method.

File: lib/govuk_docker/doctor/checkup.rb (hunk 2 above)
Comment (ChrisBAshton) [reply lib/govuk_docker/doctor/checkup.rb]: Have created a `relative_to_govuk_docker` method in `GovukDocker::Paths`.

**Comment by ChrisBAshton** [comment]
CC'ing @benthorner as we discussed this work before you went away. Is this what you had in mind?

File: lib/govuk_docker/setup/dnsmasq.rb [hunk 4]
```diff
@@ -44,7 +44,8 @@ def install_dnsmasq
   def configure_etc_resolver_devgovuk
     write_file(
       "/etc/resolver/dev.gov.uk",
-      "nameserver 127.0.0.1\nport 53"
+      File.read(GovukDocker::Paths::dnsmasq_conf),
```
Comment (benthorner) [inline lib/govuk_docker/setup/dnsmasq.rb]: Much better! I didn't realise you could use `::` to refer to a class method! I think it's more conventional to use `.`, though.

File: spec/paths_spec.rb [hunk 5]
```diff
@@ -42,4 +42,25 @@
       end
     end
   end
+
+  describe "dnsmasq_conf" do
```
Comment (benthorner) [inline spec/paths_spec.rb]: Minor, but we could simplify this test by stubbing the `govuk_docker_dir` it delegates to.

File: lib/govuk_docker/setup/dnsmasq.rb (hunk 4 above)
Comment (ChrisBAshton) [reply lib/govuk_docker/setup/dnsmasq.rb]: You can only do it if you specify `self` before the method's definition.

Thought the other methods were being called with `::` but have double-checked and they're not - will update to `.` 👍
